namespace XUnity.AutoInstaller.Models;

/// <summary>
/// XUnity.AutoTranslator 配置 (AutoTranslatorConfig.ini)
/// </summary>
public class XUnityConfig
{
    // [Service]
    public string ServiceEndpoint { get; set; } = "GoogleTranslate";
    public string ServiceFallbackEndpoint { get; set; } = string.Empty;

    // [General]
    public string GeneralLanguage { get; set; } = "zh-CN";
    public string GeneralFromLanguage { get; set; } = "ja";
    public int GeneralMaxCharactersPerTranslation { get; set; } = 200;
    public int GeneralMinDialogueChars { get; set; } = 20;
    public bool GeneralIgnoreWhitespaceInDialogue { get; set; } = true;
    public bool GeneralEnableUIResizing { get; set; } = true;
    public string GeneralOverrideFont { get; set; } = string.Empty;
    public bool GeneralCopyToClipboard { get; set; } = false;

    // [TextFrameworks]
    public bool TextFrameworksUGUI { get; set; } = true;
    public bool TextFrameworksNGUI { get; set; } = true;
    public bool TextFrameworksTextMeshPro { get; set; } = true;
    public bool TextFrameworksTextMesh { get; set; } = true;
    public bool TextFrameworksIMGUI { get; set; } = false;

    // [Files]
    public string FilesDirectory { get; set; } = "Translation";
    public string FilesOutputFile { get; set; } = "_AutoGeneratedTranslations.txt";
    public string FilesSubstitutionFile { get; set; } = "_Substitutions.txt";
    public string FilesPreprocessorsFile { get; set; } = "_Preprocessors.txt";
    public string FilesPostprocessorsFile { get; set; } = "_Postprocessors.txt";

    // [Texture]
    public string TextureDirectory { get; set; } = "Translation";
    public bool TextureEnableTranslation { get; set; } = true;
    public bool TextureEnableDumping { get; set; } = false;
    public string TextureHashGenerationStrategy { get; set; } = "FromImageName";

    // [Behaviour] - Advanced (这些选项实际在Behaviour节中)
    public bool AdvancedEnableTranslationScoping { get; set; } = true;
    public bool AdvancedHandleRichText { get; set; } = true;
    public int AdvancedMaxTextParserRecursion { get; set; } = 10;
    public bool AdvancedHtmlEntityPreprocessing { get; set; } = true;

    // [Behaviour] - Additional options
    /// <summary>
    /// 批量翻译请求以减少API调用
    /// </summary>
    public bool BehaviourEnableBatching { get; set; } = true;

    /// <summary>
    /// 使用静态翻译（缓存的翻译）
    /// </summary>
    public bool BehaviourUseStaticTranslations { get; set; } = true;

    /// <summary>
    /// 忽略以指定字符开头的文本
    /// </summary>
    public string BehaviourIgnoreTextStartingWith { get; set; } = string.Empty;

    /// <summary>
    /// 输出无法翻译的文本到日志
    /// </summary>
    public bool BehaviourOutputUntranslatableText { get; set; } = false;

    /// <summary>
    /// 翻译延迟（毫秒）
    /// </summary>
    public int BehaviourDelay { get; set; } = 0;

    // [Http]
    /// <summary>
    /// HTTP User-Agent字符串
    /// </summary>
    public string HttpUserAgent { get; set; } = string.Empty;

    /// <summary>
    /// 禁用SSL证书验证
    /// </summary>
    public bool HttpDisableCertificateChecks { get; set; } = false;

    // [Debug]
    /// <summary>
    /// 启用调试控制台
    /// </summary>
    public bool DebugEnableConsole { get; set; } = false;

    /// <summary>
    /// 启用调试日志
    /// </summary>
    public bool DebugEnableLog { get; set; } = false;

    // [Optimization]
    /// <summary>
    /// 启用翻译缓存
    /// </summary>
    public bool OptimizationEnableCache { get; set; } = true;

    /// <summary>
    /// 缓存最大条目数
    /// </summary>
    public int OptimizationMaxCacheEntries { get; set; } = 5000;

    // [Integration]
    /// <summary>
    /// 文本获取器兼容模式（用于某些游戏的兼容性）
    /// </summary>
    public bool IntegrationTextGetterCompatibilityMode { get; set; } = false;

    // [ResourceRedirector]
    /// <summary>
    /// 启用资源重定向
    /// </summary>
    public bool ResourceRedirectorEnableRedirector { get; set; } = true;

    /// <summary>
    /// 检测重复资源
    /// </summary>
    public bool ResourceRedirectorDetectDuplicateResources { get; set; } = false;

    // [Authentication]
    public string AuthenticationGoogleAPIKey { get; set; } = string.Empty;
    public string AuthenticationBingSubscriptionKey { get; set; } = string.Empty;
    public string AuthenticationDeepLAPIKey { get; set; } = string.Empty;
    public string AuthenticationBaiduAppId { get; set; } = string.Empty;
    public string AuthenticationBaiduAppSecret { get; set; } = string.Empty;
    public string AuthenticationYandexAPIKey { get; set; } = string.Empty;

    // Additional Authentication Services
    /// <summary>
    /// Watson翻译服务认证
    /// </summary>
    public string AuthenticationWatsonAPIKey { get; set; } = string.Empty;

    /// <summary>
    /// 彩云小译API Token
    /// </summary>
    public string AuthenticationLingoCloudToken { get; set; } = string.Empty;

    /// <summary>
    /// 创建推荐配置（中文翻译）
    /// </summary>
    public static XUnityConfig CreateRecommended()
    {
        return new XUnityConfig
        {
            ServiceEndpoint = "GoogleTranslate",
            GeneralLanguage = "zh-CN",
            GeneralFromLanguage = "ja",
            GeneralMaxCharactersPerTranslation = 200,
            GeneralEnableUIResizing = true,
            TextFrameworksUGUI = true,
            TextFrameworksNGUI = true,
            TextFrameworksTextMeshPro = true,
            TextureEnableTranslation = true,
            AdvancedEnableTranslationScoping = true
        };
    }
}
