namespace XUnity.AutoInstaller.Models;

/// <summary>
/// XUnity.AutoTranslator 配置 (AutoTranslatorConfig.ini)
/// </summary>
public class XUnityConfig
{
    // [Service]
    public string ServiceEndpoint { get; set; } = "GoogleTranslate";
    public string ServiceFallbackEndpoint { get; set; } = string.Empty;

    // [General]
    public string GeneralLanguage { get; set; } = "zh-CN";
    public string GeneralFromLanguage { get; set; } = "ja";
    public int GeneralMaxCharactersPerTranslation { get; set; } = 200;
    public int GeneralMinDialogueChars { get; set; } = 20;
    public bool GeneralIgnoreWhitespaceInDialogue { get; set; } = true;
    public bool GeneralEnableUIResizing { get; set; } = true;
    public string GeneralOverrideFont { get; set; } = string.Empty;
    public bool GeneralCopyToClipboard { get; set; } = false;

    // [TextFrameworks]
    public bool TextFrameworksUGUI { get; set; } = true;
    public bool TextFrameworksNGUI { get; set; } = true;
    public bool TextFrameworksTextMeshPro { get; set; } = true;
    public bool TextFrameworksTextMesh { get; set; } = true;
    public bool TextFrameworksIMGUI { get; set; } = false;

    // [Files]
    public string FilesDirectory { get; set; } = "Translation";
    public string FilesOutputFile { get; set; } = "_AutoGeneratedTranslations.txt";
    public string FilesSubstitutionFile { get; set; } = "_Substitutions.txt";
    public string FilesPreprocessorsFile { get; set; } = "_Preprocessors.txt";
    public string FilesPostprocessorsFile { get; set; } = "_Postprocessors.txt";

    // [Texture]
    public string TextureDirectory { get; set; } = "Translation";
    public bool TextureEnableTranslation { get; set; } = true;
    public bool TextureEnableDumping { get; set; } = false;
    public string TextureHashGenerationStrategy { get; set; } = "FromImageName";

    // [Advanced]
    public bool AdvancedEnableTranslationScoping { get; set; } = true;
    public bool AdvancedHandleRichText { get; set; } = true;
    public int AdvancedMaxTextParserRecursion { get; set; } = 10;
    public bool AdvancedHtmlEntityPreprocessing { get; set; } = true;

    // [Authentication]
    public string AuthenticationGoogleAPIKey { get; set; } = string.Empty;
    public string AuthenticationBingSubscriptionKey { get; set; } = string.Empty;
    public string AuthenticationDeepLAPIKey { get; set; } = string.Empty;
    public string AuthenticationBaiduAppId { get; set; } = string.Empty;
    public string AuthenticationBaiduAppSecret { get; set; } = string.Empty;
    public string AuthenticationYandexAPIKey { get; set; } = string.Empty;

    /// <summary>
    /// 创建推荐配置（中文翻译）
    /// </summary>
    public static XUnityConfig CreateRecommended()
    {
        return new XUnityConfig
        {
            ServiceEndpoint = "GoogleTranslate",
            GeneralLanguage = "zh-CN",
            GeneralFromLanguage = "ja",
            GeneralMaxCharactersPerTranslation = 200,
            GeneralEnableUIResizing = true,
            TextFrameworksUGUI = true,
            TextFrameworksNGUI = true,
            TextFrameworksTextMeshPro = true,
            TextureEnableTranslation = true,
            AdvancedEnableTranslationScoping = true
        };
    }
}
